### ISSUE TITLE
Cleanup ATs after unsuccessful run

### ISSUE THREAD

**Issue by Albertoimpl** [spring-cloud/spring-cloud-app-broker#145]
Sometimes it's inevitable that ATs will fail, leaving things in an inconsistent state that can not be cleaned up.
Can we think of an approach to always clean things up without re-creating the world?

**Comment by ojhughes** [comment]
Scheduled clean up task perhaps?

**Comment by royclarkson** [comment]
I just got bit again by this today and lost half an hour. 🙃

**Comment by spikymonkey** [comment]
Can we do this by moving to the RGB pool with laundromat?

**Comment by gberche-orange** [comment]
FYI, in my app broker acceptance fork at I've added the following related elements 
* ci launches a pre-test [clean script](https://github.com/orange-cloudfoundry/osb-cmdb-ci/blob/master/scripts/clean-at-cf-environment.sh)
* added display of deployed broker logs, and asserts no errors, see https://github.com/orange-cloudfoundry/osb-cmdb/blob/84ae9244cdce28d050022bd91f987ce147ca0852/spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/fixtures/cf/CloudFoundryService.java#L183-L208
* some tests cleanup stalled service instances by [purging them](https://github.com/orange-cloudfoundry/osb-cmdb/blob/84ae9244cdce28d050022bd91f987ce147ca0852/spring-cloud-app-broker-acceptance-tests/src/test/java/org/springframework/cloud/appbroker/acceptance/fixtures/cf/CloudFoundryService.java#L273-L303)

I'd be happy to contribute such enhancements to a standalone acceptance project discussed in #244 with @Albertoimpl

**Comment by spikymonkey** [comment]
Closing this since we now use a fresh environment for each AT run
