### ISSUE TITLE
Parallelise Acceptance Tests

### ISSUE THREAD

**Issue by AlbertoImpl** [spring-cloud/spring-cloud-app-broker#149]
We are following a pattern of one test per class in our Acceptance Tests and we can customise each one a lot.
Since the whole suite is taking over an hour now, it would be great to try to parallelise them as much as we can.

**Comment by scottfrederick** [comment]
I'm not convinced yet that having Component Tests and Acceptance Tests that parallel each other with the same level of granularity is the best way to go. I think we should look at making the Acceptance Tests much less granular, which would also have the benefit of making the tests run faster.

**Comment by AlbertoImpl** [comment]
That is very true @scottfrederick, reviewing ATs and pulling some down to CTs if we are comfortable now with them should be the way to go.
However, I still see a lot of value on parallelising all of them, especially the ATs. Since they are and will be, always the slowest.
Do you see that as a separate chore to this one?

**Comment by royclarkson** [comment]
@AlbertoImpl wasn't this recently completed?

**Comment by AlbertoImpl** [comment]
Yes, it was! Thanks @royclarkson
