### ISSUE TITLE
Consider moving all CI from Bamboo to Concourse

### ISSUE THREAD

**Issue by scottfrederick** [spring-cloud/spring-cloud-app-broker#151]
The main goals of the Bamboo build are to: 
* compile and run tests
* automatically publish snapshot builds to Spring Artifactory
* facilitate publishing of milestones, release candidates, and releases to Spring Artifactory and Maven Central

**Comment by scottfrederick** [comment]
Some things to consider: 

It would be preferable to host this build in the Spring OSS Concourse at https://ci.spring.io/. 

This project should have a `/ci` directory that contains all the Concourse definitions (jobs, tasks, etc) and resources (images, etc) for the Concourse jobs, as is done with [Spring Boot](https://github.com/spring-projects/spring-boot/tree/master/ci), [CFJC](https://github.com/cloudfoundry/cf-java-client/tree/master/ci), and other projects.

**Comment by royclarkson** [comment]
Closing this because we now have a working pipeline
