### ISSUE TITLE
Configure CI to authenticate to CF with an OAuth2 client when running ATs

### ISSUE THREAD

**Issue by scottfrederick** [spring-cloud/spring-cloud-app-broker#158]
Acceptance tests can be configured to use a user or an OAuth2 client when authenticating to Cloud Foundry. 

e.g. 

```
SPRING_CLOUD_APPBROKER_ACCEPTANCETEST_CLOUDFOUNDRY_USERNAME=admin
SPRING_CLOUD_APPBROKER_ACCEPTANCETEST_CLOUDFOUNDRY_PASSWORD=DiDsqdjF0JzE-R5LKYGKRXH1KMlJxrWM
```
for user authentication or 

```
SPRING_CLOUD_APPBROKER_ACCEPTANCETEST_CLOUDFOUNDRY_CLIENT_ID=admin
SPRING_CLOUD_APPBROKER_ACCEPTANCETEST_CLOUDFOUNDRY_CLIENT_SECRET=iCysigLbzDcS3b8veys8w_nbIh-jQaVX
```

for client authentication. 

CI currently configures the ATs with a username and password. This is the simpler code path, and not necessarily the recommended configuration as it is easier to create an OAuth2 client with the scopes necessary to support all App Broker features. 

CI setup should be modified to create an appropriate OAuth2 client in the target environment and configure ATs to use that client for CF authentication.

**Comment by scottfrederick** [comment]
@AlbertoImpl I seem to remember you making this change to the AT setup in CI. Can we close this?

**Comment by AlbertoImpl** [comment]
Yes, it was implemented a few weeks ago. We can close it. Thanks @scottfrederick !
