### ISSUE TITLE
Use latest Spring style in docs

### ISSUE THREAD

**Issue by scottfrederick** [spring-cloud/spring-cloud-app-broker#187]
As implemented in [Spring Cloud Open Service Broker docs build file](https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/master/spring-cloud-open-service-broker-docs/build.gradle) with these commits: 

* https://github.com/spring-cloud/spring-cloud-open-service-broker/commit/d55bc84b5640d57490d823ae6590585f678805cb
* https://github.com/spring-cloud/spring-cloud-open-service-broker/commit/e6700a0b18aae5c30f8e50a449789816cf0a69bf

**Comment by royclarkson** [comment]
@fifthposition I'm hoping to get a release out soon. Thoughts on this?

**Comment by fifthposition** [comment]
Here you are @royclarkson… only 9 months late! https://github.com/spring-cloud/spring-cloud-app-broker/pull/330

**Comment by royclarkson** [comment]
Closed in 4a985e5adb658c62ec0d4aab45f14da4a29cef57
