### ISSUE TITLE
Allow more control over CredHub paths

### ISSUE THREAD

**Issue by spikymonkey** [spring-cloud/spring-cloud-app-broker#201]
At the moment app broker stores binding credentials in a CredHub path which begins `/c/${spring.application.name}`. We've found that, now we have multiple applications in our product, this means we need to use more than one 'top level' path, i.e. `/c/application-1`, `/c/application-2`.

It'd be nice if we could group these together in CredHub under a single top-level path which represents our product, e.g. `/c/${product_name}/${spring.application.name}`.

We could do this as a PR if you're happy with the idea :)

**Comment by scottfrederick** [comment]
@spikymonkey That's certainly a reasonable request. What's the proposal for configuring the "product name" part of the CredHub path? Feel free to share your proposal in the form of a PR :-).

**Comment by royclarkson** [comment]
@Albertoimpl Is this related to the CredHub concerns we were discussing? If so, let's add it to 1.1.0.M2.

**Comment by Albertoimpl** [comment]
Would be interesting to do some research on other brokers using CredHub to see if this would enable them to incorporate the module before committing to adding this feature.

**Comment by Albertoimpl** [comment]
The CredHub module was deprecated.
