### ISSUE TITLE
SpacePerServiceInstance only works if user/client has cloud_controller.admin

### ISSUE THREAD

**Issue by spikymonkey** [spring-cloud/spring-cloud-app-broker#203]
I've been running some tests using App Broker configured with a UAA client which does not have the `cloud_controller.admin` authority (instead it has `cloud_controller.read` and `cloud_controller.write`). If App Broker is configured without a target specification then this can be made to work by making the client an Org Manager and Space Developer for the default org and space respectively, before creating the first service instance.

With the `SpacePerServiceInstance` target specification however, spaces are created on the fly per service instance, and no Space Developer is set. This means that the subsequent call to create a service instance in this space will fail for our non-`cloud_controller.admin` client. 

Using a client without the `cloud_controller.admin` authority is a security requirement for our target environment, and we'd like to be able to use the `SpacePerServiceInstance` feature. If the client is an Org Manager for the default org, then I think it should be possible for it to make itself a Space Developer for any space it creates within that org, so hopefully there's a way to make this work :)

I'll do some more testing and see if I can put a PR together if this sounds like a reasonable thing to do?

**Comment by scottfrederick** [comment]
> If the client is an Org Manager for the default org, then I think it should be possible for it to make itself a Space Developer for any space it creates within that org, so hopefully there's a way to make this work :)

> if this sounds like a reasonable thing to do?

@spikymonkey As usual, this does sound like a reasonable approach.

**Comment by spikymonkey** [comment]
Thanks @scottfrederick, I'm taking a look at this now. Would you mind giving me permissions in this repo to assign the issue to myself please?

**Comment by spikymonkey** [comment]
Sorry @scottfrederick I'm not sure when I'll get to this, I've had to move on to other things
