### ISSUE TITLE
ServiceInstanceGuidSuffix only works with short service names

### ISSUE THREAD

**Issue by spikymonkey** [spring-cloud/spring-cloud-app-broker#204]
It turns out that CF only supports service names up to a length of 50 characters. With a 36 char guid forming part of the final name, that makes it quite likely that users will specify a service name prefix that results in the final name overrunning the allowed number of characters, which results in an error like this:

```
2019-02-13 05:54:07.744 ERROR 8 --- [ry-client-nio-2] pDeploymentCreateServiceInstanceWorkflow : Error creating backing services for p.config-server-alpha/standard with error 'CF-ServiceInstanceNameTooLong(60009): You have requested an invalid service instance name. Names are limited to 50 characters.'
```

Would it make sense for App Broker to truncate the service name prefix to ensure that the final name fits within the limit? Or could it fail fast somehow?

**Comment by royclarkson** [comment]
Should it truncate the name to 14 chars then append the 36 chars of GUID? That way you'll always have the complete GUID?

**Comment by spikymonkey** [comment]
Yes I think so. We can't truncate the GUID and still guarantee uniqueness, so the prefix is the only bit we can apply the chainsaw to :)
