### ISSUE TITLE
Logged exceptions should contain more detail

### ISSUE THREAD

**Issue by scottfrederick** [spring-cloud/spring-cloud-app-broker#228]
#182 was implemented to fix #177, but this still does not provide as much information about an exception as it should provide. 

When using `doOnError()`, just using `exception` as a parameter for a `{}` placeholder results in an empty string in the output. Using `exception.getMessage()` results in the exception message in the output, but a more complete cause tree or stack trace would be better.

**Comment by royclarkson** [comment]
I'm not sure we need to be adding a stack trace to the log here. `doOnError()` is a side effect, but the error is still propagated up the chain.

https://projectreactor.io/docs/core/release/reference/#_log_or_react_on_the_side

**Comment by royclarkson** [comment]
@Albertoimpl I'm considering closing this. Thoughts or concerns?

**Comment by Albertoimpl** [comment]
Agreed, we did some improvements recently, @royclarkson.

**Comment by royclarkson** [comment]
👍
