### ISSUE TITLE
BackingAppManagementService requires admin permissions on Cloud Foundry

### ISSUE THREAD

**Issue by alek-sys** [spring-cloud/spring-cloud-app-broker#232]
When using `BackingAppManagementService` on Cloud Foundry, it is making a call to Cloud Countroller API to get service name and plan name of a service instance with provided ID (`AppDeployer.getServiceInstance` method).

To get service instance details Cloud Foundry requires the OAuth client used by the App Broker either to have access to the org and space where SI is deployed or to have `cloud_controller.admin` scope. 

The former is hard to implement since a developer can create an SI in any org and space, the latter is a potential security concern. 

The only reliable way of fixing this I can see is to accept service and plan name as arguments for any `BackingAppManagementService` call.

**Comment by spikymonkey** [comment]
Fixed by #767
