### ISSUE TITLE
Default in-memory state repositories aren't threadsafe

### ISSUE THREAD

**Issue by GFriedrich** [spring-cloud/spring-cloud-app-broker#254]
When reading the code I saw that for some reason both in-memory state repositories use a regular HashMap to store the state. And for some other reason they are made "volatile" which looks rather useless to me.
So either I'm missing something fundamental here or both implementations are quite broken and should use a ConcurrentHashMap where the "volatile" keyword is removed.

**Comment by Albertoimpl** [comment]
Thanks a lot for the feedback @GFriedrich you are right!
Would you like to provide some tests to prove the failures and submit a PR to fix this issue?

**Comment by GFriedrich** [comment]
May take until next weekend, but sure, I can tackle this, if you want me to.

**Comment by Albertoimpl** [comment]
Contributions are always appreciated, thanks @GFriedrich!

**Comment by royclarkson** [comment]
Thanks for identifying the issue and submitting the PR! I'm adding a note here for anyone who finds this in the future, that the in memory state repositories are absolutely not meant for production use and should only be used for testing. I'll add another issue to update reference and java doc to reflect that.
