### ISSUE TITLE
rebindOnUpdate field breaches hashCode/equals/toString contract

### ISSUE THREAD

**Issue by GFriedrich** [spring-cloud/spring-cloud-app-broker#261]
Hi,

as far as I can see the methods `equals`, `hashCode` and `toString` miss the just recently added field `rebindOnUpdate` in the `BackingService` class.

https://github.com/spring-cloud/spring-cloud-app-broker/blob/aca45ee1f3a403eb779228b7c52af8631f26b2e9/spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/deployer/BackingService.java#L117-L149

**Comment by Albertoimpl** [comment]
Excellent point, would you like to create a PR for it @GFriedrich?

Thanks!

**Comment by GFriedrich** [comment]
Will do :)
