### ISSUE TITLE
Interests in orange contributions supporting osb-cmdb use-cases ?

### ISSUE THREAD

**Issue by gberche-orange** [spring-cloud/spring-cloud-app-broker#285]
Thanks for sharing SCAB with the community. This is an impressive piece of work!

I conducted a spike to use SCAB for Orange's osb-cmdb use-case (see https://github.com/orange-cloudfoundry/paas-templates/issues/492 for background) and SCAB was mostly matching the use-cases with the following few changes (which are visible on the [orange-cloudfoundry/osb-cmdb-spike repo](https://github.com/orange-cloudfoundry/osb-cmdb-spike) see [diff](https://github.com/spring-cloud/spring-cloud-app-broker/compare/master...orange-cloudfoundry:master)):
- support brokered services without backing applications (i.e. only backing services) https://github.com/spring-cloud/spring-cloud-app-broker/pull/288
- support asynchronous backing services (i.e. increase the default 5min cf-java-client timeout to fetch service instance status) #289
- provide ability to AppDeploymentCreateServiceBindingWorkflow to provision service keys (through extending Deployer service or potentially opening up some base classes to enable extensions without duplicating them)   : #292 
- support for brokered service plan upgrades cascading to backing service. See #290

Additionally, there are the following pending issues/use-cases that I would need to handle:
- Fully support async backing services: enable SCAB to provide operation status even in case of SCAB broker restart 
- More flexibility into where backing services are created: See #295
   - Target isn't supporting dynamically created Space yet shared among multiple service instances.
   - Impl is currently hardcoded into `CloudFoundryAppDeployer.createServiceInstance()` by looking up properties (some changes required to support by strategy definitions)
- CreateServiceInstance/UpdateServiceInstance does not yet return dashboard url for brokered services 
  - Need to subclass workflow impls buildResponse() to set dashboard URL.
- Support for dynamically constructed catalog: See #317
  - Need to inject BrokeredServices, see #311

If there is interest in Orange's contributions to SCAB to that the osb-cmdb repo can use SCAB upstream version, I will to submit individual issues for changes/use-cases above or directly PRs for simple changes.

Thanks in advance!

**Comment by royclarkson** [comment]
@gberche-orange thanks for the feedback. Generally speaking, we're happy to discuss any ideas for improving the project. I haven't had a chance to review your suggestions in detail yet.

**Comment by gberche-orange** [comment]
@royclarkson I've submitted a first round of 3 independent PRs. That'd be useful to have feedback on whether there is interest so I can proceed with investing more time in integration tests updates, and submitting more PRs.

**Comment by royclarkson** [comment]
@gberche-orange thanks again. I may not get to these immediately, but will review soon. We're having a bit of a debate about versioning and breaking changes. There's some places that could use some refactoring I think. Regardless, my goal is to include as much of your contributions as we can. We appreciate the interest in the project and are looking forward to a useful feedback cycle with you and your team.

**Comment by gberche-orange** [comment]
thanks @royclarkson 

 > We're having a bit of a debate about versioning and breaking changes. There's some places that could use some refactoring I think. 

Could you please share which parts are considered for being refactored, and what would be the timeline for this ?
Also, what breaking changes are currently being considered/debated ? That would be important to assess impacts for my osb-cmdb project.

**Comment by royclarkson** [comment]
@gberche-orange it appears that you've created issues for all of your items you listed here. If that's the case, can we close this issue? We'll continue to review and include as many of your PRs as possible.

**Comment by gberche-orange** [comment]
@royclarkson Thanks for following up. I still have a some pending issues to submit (approx 25%), I'll cross reference in this issue in the future. 

Regarding https://github.com/spring-cloud/spring-cloud-app-broker/issues/285#issuecomment-549575172

> We're having a bit of a debate about versioning and breaking changes. There's some places that could use some refactoring I think.

I'm still interested in hearing which parts of SCAB would have breaking changes in the future and would undergo refactorings. Looking at issues assigned in [SCAB milestones](https://github.com/spring-cloud/spring-cloud-app-broker/milestones), I have not yet been able to spot related conversations and exchanges. Is there some places (slack channel, mailing list, design docs) where the related debates/discussions can be shared with the community ?

Last, the rationales for keeping this issue opened would be to clarify together which Osb-Cmdb features make less sense to be integrated into SCAB and would better fit outside of the project, and which support SCAB could bring for such 3rd party extensions, including automated test support.

**Comment by Albertoimpl** [comment]
Hey, @gberche-orange. Thanks for responding!
Would be great to have the individual issues to be implemented open rather than this one, so that we can use the issues for planning. Even if this is closed, you could still reference it. Does it make sense?
At the moment, we are not really having conversations regarding breaking changes, it is more about what to implement for each version and the outcome is what you saw in our milestones: https://github.com/spring-cloud/spring-cloud-app-broker/milestones  

We just created, as an experiment, a gitter channel we are going to start using for all our conversations: https://gitter.im/spring-cloud-app-broker/community please join us and let us know what you think about the future milestones.

**Comment by gberche-orange** [comment]
@Albertoimpl thanks for clarifying and sharing the gitter channel. I'll create the remaining pending issues as to ease prioritization and assignement to milestones, and will update this one. I'm closing it as requested.

**Comment by royclarkson** [comment]
There are are couple or three issues that potentially imply breaking changes, or at least we should consider as major breaking changes. See #244, #241, and #243. I'm seeing these as candidates for a 2.x release.
