### ISSUE TITLE
Document that the default behaviour of ServiceInstanceStateRepository

### ISSUE THREAD

**Issue by Albertoimpl** [spring-cloud/spring-cloud-app-broker#314]
At the moment, we default to an `InMemoryServiceInstanceStateRepository`.
However, we should recommend and provide an example of a better one using a persistence model.

**Comment by Albertoimpl** [comment]
See https://github.com/spring-cloud-samples/spring-cloud-app-broker-samples#service-instance-state-repositories

**Comment by royclarkson** [comment]
Yep, looks good! We need to include the note in the reference docs, and probably the java doc as well, so no one misses it.

**Comment by royclarkson** [comment]
maybe we should just make the default and in memory mongo db and use the reactive support. that would solve all these issues.

**Comment by royclarkson** [comment]
Duplicate of #257
