### ISSUE TITLE
Option to pass Org and Space as parameter while creating service instance

### ISSUE THREAD

**Issue by buddyavis** [spring-cloud/spring-cloud-app-broker#338]
Is there an option to pass Org and Space dynamically as parameters while creating Service Instance?

Given I have a service and plan, I want to create service instance in different org/space to deploy the backing application.

**Comment by Albertoimpl** [comment]
At the moment @buddyavis, there is not a default strategy implemented to handle custom org _and_ spaces.

We have, however a couple of strategies that work out of the box:
https://docs.spring.io/spring-cloud-app-broker/docs/current/reference/html5/#_backing_application_target
The main one our teams have been using is  `SpacePerServiceInstance`

> The SpacePerServiceInstance Target
If you use the SpacePerServiceInstance target, App Broker will deploy backing applications to a unique target location that is named using the service instance GUID provided by the platform at service instance create time. For Cloud Foundry, this target location will be the org named by spring.cloud.appbroker.deployer.cloudfoundry.default-org and a new space created using the service instance GUID as the space name.


That said, you could implement your own logic as a `TargetService`, the same way we do in the example before https://github.com/spring-cloud/spring-cloud-app-broker/blob/master/spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/extensions/targets/SpacePerServiceInstance.java although, I never tried that myself.

However, **we only support to choose the space and not the org** by doing the following inside a `TargetService`:
```
properties.put(DeploymentProperties.TARGET_PROPERTY_KEY, customSpace);
```

Do you think that having `SpacePerServiceInstance` is enough?
Should we document how create your own `TargetService` to deploy in a custom space?
Is just deploying into a custom space enough? If not, what is the use case?

**Comment by buddyavis** [comment]
Thank you @Albertoimpl for detailing the options. 
SpacePerServiceInstance Will not be right option for our use cases, since it creates a unique space for the given service. Moreover we do not want app broker to create new space. 

To start with, deploying into custom space will make the consuming business teams to choose the space as per their preference. 

Would be great if you could document TargetService in detail. Thanks again.

**Comment by Albertoimpl** [comment]
Thanks a lot for the feedback @buddyavis.
We just improved our docs and added a section on how to customise your target: https://docs.spring.io/spring-cloud-app-broker/docs/1.1.0.BUILD-SNAPSHOT/reference/#creating-a-custom-target
Also, we added a fully functional example to our sample apps: https://github.com/spring-cloud-samples/spring-cloud-app-broker-samples#backing-application-targets

Let us know what you think and if this is what you needed!

**Comment by buddyavis** [comment]
Thank you @Albertoimpl. The given sample implementation is working as documented. However I have noticed an issue or limitation
When I delete the service instance created using service with custom target, app broker is attempting to delete the space as well, space that is configured in the CustomSpaceService.  

Expectation is app broker should not delete the space, since the given custom space is created outside of app broker. 

Also would like to know, is there any option available to configure the custom target on app level?

Will it be feasible to configure custom space for individual apps configured in the plan?

**Comment by royclarkson** [comment]
@buddyavis would you mind opening a new issue for optionally not deleting the space if it was already present? Basically, it's the same issue as #316 but for existing spaces. Thanks for the feedback!

**Comment by buddyavis** [comment]
Thank you! @royclarkson. Opened a separate issue #340.

**Comment by Albertoimpl** [comment]
Thanks for opening #340 and for the feedback. Closing this one in favour of the other one.
