### ISSUE TITLE
Expose to a developer the logs from a config server service instance

### ISSUE THREAD

**Issue by phopper-pivotal** [spring-cloud/spring-cloud-app-broker#342]
in TAS (* Application Service) when a developer creates a spring cloud config server service instance they bind a github repo to expose properties to the application. (yes basic functionality of SCS config server.)

The service instance is created successfully. What happens if a developer commits to GitHub invalid YAML. When this error occurs the downstream developer is unable to diagnose the issue without the involvement of the operator. Exposing the logs (from the app via stream) would allow the developer to see the logs and diagnose the issue themselves, making this more self-service.

An example;
`access-logging:`
` enabled: true`

(this example the 2nd line doesn't conform to YAML because the indent is one-space.)

this wall cause an error within the broker at property resolution.

**Comment by royclarkson** [comment]
Closed in #366
