### ISSUE TITLE
Update CONTRIBUTING docs

### ISSUE THREAD

**Issue by Albertoimpl** [spring-cloud/spring-cloud-app-broker#346]
The steps to contribute that we have over here https://github.com/spring-cloud/spring-cloud-app-broker/blob/master/CONTRIBUTING.adoc are pointing to a different set of style guides than the ones we require now https://github.com/spring-cloud/spring-cloud-app-broker/tree/master/src

**Comment by gberche-orange** [comment]
thanks @Albertoimpl, sorry I had forgotten about related exchange at https://github.com/spring-cloud/spring-cloud-app-broker/pull/291#issuecomment-551890641

Regarding code formatting including imports, I guess the eclipse code formatted plugin is not necessary anymore and the `src/idea/idea.xml`  needs to be imported in `Editor > code style > import -> intellij idea format`
![image](https://user-images.githubusercontent.com/4748380/76977466-a58ebe00-6935-11ea-9ad1-d8ae99fca2b0.png)

Submitted #347 if this can help.

**Comment by royclarkson** [comment]
Yeah, that's correct. You don't need the eclipse code formatter plugin. That needs to be updated.

**Comment by spikymonkey** [comment]
I think we can close this thanks to #347 - thanks!
