### ISSUE TITLE
Use standard Gradle maven plugins if possible

### ISSUE THREAD

**Issue by spikymonkey** [spring-cloud/spring-cloud-app-broker#360]
I just tried to `./gradlew publishToMavenLocal` and realised that we're not using the standard Gradle maven publishing plugin. I'm wondering if we can? Could be an interesting spike to see whether there are still gaps between the standard tooling and our own.

**Comment by royclarkson** [comment]
Yeah, we still have the "legacy" configuration in app broker. Other Spring projects have upgraded their builds to use the new features. No reason we can't do it as well.
