### ISSUE TITLE
`rebind-on-update` should trigger rebind after backing application update

### ISSUE THREAD

**Issue by LittleBaiBai** [spring-cloud/spring-cloud-app-broker#396]
Currently, rebind is triggered after backing service instance update and before backing application update. If a service instance configuration can be altered by the bound app properties, e.g. `SSO_SCOPES` environment variable for the SSO-VT service binding, then the service instance would not have received all the necessary configurations through `rebind`. 

To accommodate the above use case, the flow needs to be:
- Update backing service instances
- Update backing applications with `no-start`
- Rebind if `rebind-on-update` is set to true
- Restage backing applications to make sure they get the new binding credentials.

**Comment by spikymonkey** [comment]
@LittleBaiBai I spent the morning digging around in the app broker code. I think I see what you mean, although I'm not sure how to do an update with `no-start`... Wondering if this might go quicker if we pair on it?

**Comment by spikymonkey** [comment]
I've been struggling all day with getting clean test runs, but think I finally got it on [CI](https://scs.ci.springapps.io/teams/main/pipelines/scg-pull-requests/jobs/run-acceptance-tests/builds/436). @LittleBaiBai is this the failure you'd expect to see without the App Broker change?

```
13-01-2021 15:42:41.922 [Test worker] INFO  i.p.s.c.s.UaaAwareBrowserClient.clickButtonIfExists - Page body is: Invalid redirect https://ssologin-2021-01-13T15-37-10-UTC-new.apps.magenta.springapps.io/login/oauth2/code/sso did not match one of the registered values
Authorization Request Error
 There was an error. The request for authorization was invalid.
Copyright © Pivotal 2021. All Rights Reserved.
Last login January 13, 2021 3:41:05 PM UTC
GatewayServerWithSsoLoginFilterSpec failed, so cleanup method will be suppressed


io.pivotal.spring.cloud.acceptance.gateway.GatewayServerWithSsoLoginFilterSpec > create service with SSO Login filter FAILED
    Condition not satisfied:

    client.pageText().contains("Test message")
    |      |          |
    |      |          false
    |      Invalid redirect https://ssologin-2021-01-13T15-37-10-UTC-new.apps.magenta.springapps.io/login/oauth2/code/sso did not match one of the registered values
    |      Authorization Request Error
    |       There was an error. The request for authorization was invalid.
    |      Copyright © Pivotal 2021. All Rights Reserved.
    |      Last login January 13, 2021 3:41:05 PM UTC
    <io.pivotal.spring.cloud.support.UaaAwareBrowserClient@7dd5ac02 logger=Logger[io.pivotal.spring.cloud.support.UaaAwareBrowserClient] webClient=com.gargoylesoftware.htmlunit.WebClient@4d5b87f7 page=HtmlPage(https://login.cf.magenta.springapps.io/oauth/authorize?response_type=code&client_id=019cf5f3-2d0a-4916-807c-d48bec56ce17&scope=openid%20roles%20user_attributes&state=ZEAN_8OBwZzUx01_1K4ca-vd9NnuENurPG_15tRnD5A%3D&redirect_uri=https://ssologin-2021-01-13T15-37-10-UTC-new.apps.magenta.springapps.io/login/oauth2/code/sso&nonce=PU9c-pe2H5I5-cWP5BLk-7UMQ-GlrLne2b3tSg7EHrY)@1641575162>
        at io.pivotal.spring.cloud.acceptance.gateway.GatewayServerWithSsoLoginFilterSpec.create service with SSO Login filter(GatewayServerWithSsoLoginFilterSpec.groovy:67)

io.pivotal.spring.cloud.acceptance.gateway.GatewayServerWithSsoScopeFilterSpec > test Scopes filter and token relay PASSED

> Task :acceptance:acceptanceTests FAILED
```

**Comment by spikymonkey** [comment]
@LittleBaiBai I dug a little further into this today and at least improved my understanding of the problem quite a bit.

We wondered if we could flip

1. update services (which includes a rebind if necessary)
1. update apps (which does a rolling deployment and restarts apps)

around to 

1. update apps (restart)
1. update services (rebind)

This works as far as the services being able to pull from the updated app environment goes, but as you rightly pointed out, we need to 

> Restage backing applications to make sure they get the new binding credentials

_after_ the binding occurs. So I think the next thing to do to solve this properly is to figure out how best to do this efficiently. A brute force approach would be to use the apps-then-services approach and then finally restart all the apps, but I'm sure we can do something better than that. Possibly

1. update app environment (does not require a restart)
1. update services (rebind)
1. update apps (restart)

but need to give it some proper thought next.

**Comment by spikymonkey** [comment]
I've pushed a fix for this to a [branch](https://github.com/spring-cloud/spring-cloud-app-broker/tree/gareth/%60rebind-on-update%60-should-trigger-rebind-after-backing-application-update-396). App Broker unit/integration tests are passing, and so is @LittleBaiBai's AT which drives out the need for this behaviour. I'm having trouble running the App Broker ATs though - seems our pipelines are broken so need to tackle that next.
