### ISSUE TITLE
Update App Broker to Spring Boot 3.0

### ISSUE THREAD

**Issue by spikymonkey** [spring-cloud/spring-cloud-app-broker#654]

**Comment by fombico** [comment]
Would there be a need to update the Spring Cloud Open Service broker as well?

**Comment by royclarkson** [comment]
@fombico yes, it will require an updated release.

**Comment by spikymonkey** [comment]
App Broker 2.0.0-SNAPSHOT builds with Boot 3 are being produced now, but we might want to keep this open until we have a first GA release build.
