### ISSUE TITLE
Upgrade docs to asciidoctor

### ISSUE THREAD

**Issue by Albertoimpl** [spring-cloud/spring-cloud-app-broker#696]
We are using a very old version of `spring-doc-resources` and we should instead, as the other Spring projects, migrate to https://github.com/spring-io/spring-asciidoctor-backends

**Comment by royclarkson** [comment]
@Buzzardo may be able to help us with this?

**Comment by Buzzardo** [comment]
Yup. I assigned it to myself.

**Comment by Buzzardo** [comment]
I made https://github.com/spring-cloud/spring-cloud-app-broker/pull/697 to fix it. I tested the doc output (and ran the whole build to be sure I didn't break anything). The docs come out right, including the new look and feel for the HTML. :)

**Comment by royclarkson** [comment]
@Buzzardo woohoo! Thanks!

**Comment by Albertoimpl** [comment]
Thank you very much, @Buzzardo!

[Finished by #697]
