### ISSUE TITLE
Add target branch to dependabot PR title

### ISSUE THREAD

**Issue by abelsromero** [spring-cloud/spring-cloud-app-broker#783]
This helps to managing the same bump for multiple branches or identifying bumps that should not be accepted.
Only requires adding this configuration

```
    commit-message:
      prefix: "(v2.0.x)"
```

**Comment by patibachleda** [comment]
Thank you for making this an issue as it gave me a chance to look into GitHub PR flow from an open source project!

**Comment by patibachleda** [comment]
I made separate pull requests for each branch adding the commit message prefixes for each, I hope that is the correct way of doing this. I wasn't sure if I should also do the commit messages for 1.2.x, 1.1.x, and 1.0.x.

**Comment by abelsromero** [comment]
Closed with https://github.com/spring-cloud/spring-cloud-app-broker/pull/792
