### ISSUE TITLE
Links to Reference Docs return 404

### ISSUE THREAD

**Issue by laran** [spring-cloud/spring-cloud-app-broker#889]
All the links to Reference docs from the project site seem to be broken. I get a 404 when clicking them.

https://spring.io/projects/spring-cloud-app-broker#learn

**Comment by Albertoimpl** [comment]
Thanks a lot, @laran! Will get that fixed. Meanwhile, the docs are over here: https://docs.spring.io/spring-cloud-app-broker/docs/current/reference/

**Comment by royclarkson** [comment]
This has been resolved
